export const states = {
  'Andaman and Nicobar Islands': 'AN',
  'Andhra Pradesh': 'AP',
  'Arunachal Pradesh': 'AR',
  'Assam':'AS',
  'Bihar': 'BR',
  'Chandigarh':                'CG',
  'Chhattisgarh':              'CT',
  'Daman and Diu':             'DD',
  'Delhi':                     'DL',
  'Dadra and Nagar Haveli':    'DN',
  'Goa':                       'GA',
  'Gujarat':                   'GJ',
  'Himachal Pradesh':          'HP',
  'Haryana':                   'HR',
  'Jharkhand':                 'JH',
  'Jammu and Kashmir':         'JK',
  'Karnataka':                 'KA',
  'Kerala':                    'KL',
  'Ladakh':                    'LA',
  'Lakshadweep':               'LD',
  'Maharashtra':               'MH',
  'Meghalaya':                 'ML',
  'Manipur':                   'MN',
  'Madhya Pradesh':            'MP',
  'Mizoram':                   'MZ',
  'Nagaland':                  'NL',
  'Odisha':                    'OD',
  'Punjab':                    'PB',
  'Puducherry':                'PY',
  'Rajasthan':                 'RJ',
  'Sikkim':                    'SK',
  'Tamil Nadu':                'TN',
  'Tripura':                   'TR',
  'Telangana':                 'TS',
  'Uttarakhand':               'UK',
  'Uttar Pradesh':             'UP',
  'West Bengal':               'WB',
};
